### PR TITLE
add a paragraph to warn users against systopia/de.systopia.xcm#78

### PR DESCRIPTION
**Pull request by MarcMichalsky**
We recently ran into that problem. Our fundraising team was not amused.

### CODE REVIEW

**Comment by jensschuppe** [comment]
Thanks @MarcMichalsky!

**Comment by bjendres** [comment]
There might be a point in filtering out the ``country_id`` before passing it on to the XCM if it would be the only address parameter...

@MarcMichalsky Wouldn't that call for another ticket here?

**Comment by jensschuppe** [comment]
One might want to have a reason for recording countries of contacts. If I recall correctly, the `user_country` parameter was probably meant for distinguishing languages/countries of donors in Twingle and they asked us to process it somehow.

I could imagine handling the `user_country` parameter as `preferred_language` instead, but that should be configurable.

**Comment by bjendres** [comment]
In any case, this should be a separate ticket

**Comment by MarcMichalsky** [comment]
> If I recall correctly, the user_country parameter was probably meant for distinguishing languages/countries of donors in Twingle and they asked us to process it somehow.

This was the reason why I was so confused. I undesrstood the `user_country` as localisation information for language etc. and not as an address information. But it also makes perfectly sense to use it when building the address – but not if it's the only address information.

**Comment by jensschuppe** [comment]
> I undesrstood the user_country as localisation information for language etc. and not as an address information.

If that's the point, this should be called `user_language`. A country can not be mapped 1:1 to a language (think of Switzerland or Belgium!).

Anyway, is this obsolete with #48 being merged, @MarcMichalsky?

**Comment by jensschuppe** [comment]
Released with `1.3-beta1`.

**Pull request merged**
