### PR TITLE
fix custom_field_mapping

### LINKED ISSUE #32: Example configuration for custom_fields
Hello community,

I am trying for hours to get the `custom_fields` working. I am doing API calls via curl to our test server and apparently they are making it through.

I added `"custom_fields":{"event":"773"}` to the call and `event=custom_393` to the custom field mapping. No error at all, but the value does not show up on the custom field.

Maybe someone could give me their configuration?

### PR DESCRIPTION
**Pull request by MarcMichalsky**
removed unnecessary  json_decode
fix #32

### CODE REVIEW

**Comment by jensschuppe** [comment]
@MarcMichalsky Thanks for your PR. Can you confirm that this fixes the error described in #25, which has an already merged fix? If so, I'd mark this as a duplicate.

**Comment by MarcMichalsky** [comment]
Hi @jensschuppe, we already were on the latest branch with your fix for #25 but the custom fields did not work. On our test server I changed our git remote to my fork that includes my fix and now custom fields work.

**Comment by jensschuppe** [comment]
@MarcMichalsky You are right, the `json_decode()` will have already been done during validation at this stage. Thanks!

**Comment by MarcMichalsky** [comment]
You are welcome!

**Pull request merged**
