### PR TITLE
fix #86

### LINKED ISSUE #86: Fix issues introduced in 8bcdff4
In commit 8bcdff4, some of the logic for testing whether or not  `$profile->getAttribute()` returns a configuration value was changed to use `isset()` or `is_string()` instead of `!empty()`.  

The problem is that `$profile->getAttribute()` looks for the attribute name in it's `$data` property, which also contains the attribute names for config values that are not set (the value is then an empty string).

I suggest changeing `$profile->getAttribute()` as follows:
```php
public function getAttribute($attribute_name, $default = NULL) {
    return $this->data[$attribute_name] ?? $default;
}
```

```php
public function getAttribute($attribute_name, $default = NULL) {
    return !empty($this->data[$attribute_name]) ? $this->data[$attribute_name] : $default;
}
```

Or should we just revert commit 8bcdff4 instead?

### PR DESCRIPTION
**Pull request by MarcMichalsky**
Fix issue #86

### CODE REVIEW

**Comment by jensschuppe** [comment]
See https://github.com/systopia/de.systopia.twingle/issues/86#issuecomment-2082760941

**Comment by MarcMichalsky** [comment]
Well, the only case I can think of where `empty()` might cause problems is a string containing `'0'`. Since the profile returns empty options as empty strings, it should be fine to just check for those.

**Comment by jensschuppe** [comment]
> the profile returns empty options as empty strings,

Actually, that's only true for attributes that have been left empty in the form. The profile constructor fills empty attributes with `NULL`, i.e. those that haven't got a value at all (because the form has not been saved since they were added). I think the empty string is not a valid value for all attributes in the first place, so the `getAttribute()` method should not assume that.

Could you list the comparisons changed in 8bcdff4a855f621fec11ba255112c1d4ff57046e that actually cause problems? I'd be in favor of fixing those instead, as there's more context for each attribute.

**Comment by MarcMichalsky** [comment]
I suspect that there could be problems if a value received from a `getAttribute()` call is subsequently tested with `isset()` or `is_string()` because they would incorrectly assume an empty string as an option that needs to be processed.

Possible troublemakers:
- https://github.com/systopia/de.systopia.twingle/commit/8bcdff4a855f621fec11ba255112c1d4ff57046e#r141518968
- https://github.com/systopia/de.systopia.twingle/commit/8bcdff4a855f621fec11ba255112c1d4ff57046e#r141518602
- https://github.com/systopia/de.systopia.twingle/commit/8bcdff4a855f621fec11ba255112c1d4ff57046e#r141518499
- https://github.com/systopia/de.systopia.twingle/commit/8bcdff4a855f621fec11ba255112c1d4ff57046e#r141518442
- https://github.com/systopia/de.systopia.twingle/commit/8bcdff4a855f621fec11ba255112c1d4ff57046e#r141366737
- https://github.com/systopia/de.systopia.twingle/commit/8bcdff4a855f621fec11ba255112c1d4ff57046e#r141517026

I hope I have found them all!
The [line](https://github.com/systopia/de.systopia.twingle/commit/8bcdff4a855f621fec11ba255112c1d4ff57046e#r141366737) with the `membership_type_id` was where I first noticed the problem.

**Comment by jensschuppe** [comment]
I adressed your findings in 2b8ab813dbe9a3297edfd875539348408f8bb150, could you have another look, @MarcMichalsky?

**Pull request merged**
